name: CI/CD to Upcloud

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
    
      # - name: Deploy to UpCloud
      #   env:
      #     UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
      #     UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
      #   run: |
      #     # Install upctl
      #     curl -s https://get.upbound.io/up/install.sh | sh
          
      #     # Set UpCloud region and server details
      #     export UPCLOUD_REGION=$UPCLOUD_REGION
      #     export UPCLOUD_SERVER_ID=$UPCLOUD_SERVER_ID
        
      #     # Deploy using upctl
      #     upctl deploy -s <YOUR_STACK_NAME> -t <YOUR_TEMPLATE_FILE> --wait --timeout 300

      



